# Generated by Django 5.1.1 on 2024-10-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('penthouse', '0001_initial'), ('penthouse', '0002_run'), ('penthouse', '0003_alter_run_duration'), ('penthouse', '0004_alter_run_tier'), ('penthouse', '0005_remove_run_cells_hour_remove_run_cells_wave_and_more'), ('penthouse', '0006_profile_settings_tracker_threshold_top_cells_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('settings_tracker_threshold_top_cells', models.PositiveSmallIntegerField(default=90, help_text='Threshold for top cells/run, specified in percent', verbose_name='Top threshold for cells/run')),
                ('settings_tracker_threshold_top_cells_hour', models.PositiveSmallIntegerField(default=90, help_text='Threshold for top cells/h, specified in percent', verbose_name='Top threshold for cells/h')),
                ('settings_tracker_threshold_top_coins', models.PositiveSmallIntegerField(default=90, help_text='Threshold for top coins/run, specified in percent', verbose_name='Top threshold for coins/run')),
                ('settings_tracker_threshold_top_coins_hour', models.PositiveSmallIntegerField(default=90, help_text='Threshold for top coins/h, specified in percent', verbose_name='Top threshold for coins/h')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time of the run', verbose_name='Run Date')),
                ('tier', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10'), ('T11', 'T11'), ('T12', 'T12'), ('T13', 'T13'), ('T14', 'T14'), ('T15', 'T15'), ('T16', 'T16'), ('T17', 'T17'), ('T18', 'T18')], help_text='Tier of the run', max_length=3, verbose_name='Tier')),
                ('waves', models.PositiveSmallIntegerField(help_text='End wave of the run', verbose_name='End Wave')),
                ('duration', models.PositiveIntegerField(default=1, help_text='Duration of the run (in seconds)', verbose_name='Duration')),
                ('coins', models.PositiveBigIntegerField(help_text='Total coins of the run', verbose_name='Coins')),
                ('cells', models.PositiveIntegerField(help_text='Total cells of the run', verbose_name='Cells')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the run', verbose_name='Notes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
            },
        ),
    ]
