# Generated by Django 5.1.1 on 2025-03-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this sample', verbose_name='Date')),
                ('ltc', models.PositiveBigIntegerField(help_text='Current Lifetime Coins (LTC)', verbose_name='LTC')),
                ('lts', models.PositiveIntegerField(help_text='Current Lifetime Stones (LTS)', verbose_name='LTS')),
                ('notes', models.TextField(help_text='Additional notes', verbose_name='Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_samples', to='penthouse.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
