# Generated by Django 5.1.1 on 2024-09-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time of the run', verbose_name='Run Date')),
                ('tier', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10'), ('T11', 'T11'), ('T12', 'T12'), ('T13', 'T13'), ('T14', 'T14'), ('T15', 'T15'), ('T16', 'T16'), ('T17', 'T17')], help_text='Tier of the run', max_length=3, verbose_name='Tier')),
                ('waves', models.PositiveSmallIntegerField(help_text='End wave of the run', verbose_name='End Wave')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the run (in seconds)', verbose_name='Duration')),
                ('coins', models.PositiveBigIntegerField(help_text='Total coins of the run', verbose_name='Coins')),
                ('cells', models.PositiveIntegerField(help_text='Total cells of the run', verbose_name='Cells')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the run', verbose_name='Notes')),
                ('coins_hour', models.PositiveBigIntegerField(default=0, help_text='Coins per hour', verbose_name='Coins/h')),
                ('coins_wave', models.PositiveBigIntegerField(default=0, help_text='Coins per wave', verbose_name='Coins/Wave')),
                ('cells_hour', models.PositiveIntegerField(default=0, help_text='Cells per hour', verbose_name='Cells/h')),
                ('cells_wave', models.PositiveIntegerField(default=0, help_text='Cells per wave', verbose_name='Cells/Wave')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
            },
        ),
    ]
