# Generated by Django 5.1.1 on 2024-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='tier',
            field=models.CharField(choices=[('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3'), ('T4', 'Tier 4'), ('T5', 'Tier 5'), ('T6', 'Tier 6'), ('T7', 'Tier 7'), ('T8', 'Tier 8'), ('T9', 'Tier 9'), ('T10', 'Tier 10'), ('T11', 'Tier 11'), ('T12', 'Tier 12'), ('T13', 'Tier 13'), ('T14', 'Tier 14'), ('T15', 'Tier 15'), ('T16', 'Tier 16'), ('T17', 'Tier 17'), ('T18', 'Tier 18')], help_text='Tier of the run', max_length=3, verbose_name='Tier'),
        ),
    ]
