# Generated by Django 5.1.1 on 2025-03-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0002_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
