# Generated by Django 5.1.1 on 2024-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0002_alter_run_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relics',
            field=models.ManyToManyField(to='penthouse.relic'),
        ),
    ]
