# Generated by Django 5.1.1 on 2024-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0003_alter_run_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='tier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10'), ('T11', 'T11'), ('T12', 'T12'), ('T13', 'T13'), ('T14', 'T14'), ('T15', 'T15'), ('T16', 'T16'), ('T17', 'T17'), ('T18', 'T18')], help_text='Tier of the run', max_length=3, verbose_name='Tier'),
        ),
    ]
