# Generated by Django 5.1.1 on 2024-11-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0003_profile_relics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relics',
        ),
        migrations.AddField(
            model_name='relic',
            name='claimed_by',
            field=models.ManyToManyField(blank=True, to='penthouse.profile'),
        ),
    ]
