# Generated by Django 5.1.1 on 2025-03-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['date'], 'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
    ]
