# Generated by Django 5.1.1 on 2025-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0004_alter_sample_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='ltc',
            field=models.DecimalField(decimal_places=12, help_text='Current Lifetime Coins (LTC)', max_digits=36, verbose_name='LTC'),
        ),
    ]
