# Generated by Django 5.1.1 on 2024-10-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0004_alter_run_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='cells_hour',
        ),
        migrations.RemoveField(
            model_name='run',
            name='cells_wave',
        ),
        migrations.RemoveField(
            model_name='run',
            name='coins_hour',
        ),
        migrations.RemoveField(
            model_name='run',
            name='coins_wave',
        ),
    ]
