# Generated by Django 5.1.1 on 2024-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0005_remove_run_cells_hour_remove_run_cells_wave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings_tracker_threshold_top_cells',
            field=models.PositiveSmallIntegerField(default=90, help_text='Threshold for top cells/run, specified in percent', verbose_name='Top threshold for cells/run'),
        ),
        migrations.AddField(
            model_name='profile',
            name='settings_tracker_threshold_top_cells_hour',
            field=models.PositiveSmallIntegerField(default=90, help_text='Threshold for top cells/h, specified in percent', verbose_name='Top threshold for cells/h'),
        ),
        migrations.AddField(
            model_name='profile',
            name='settings_tracker_threshold_top_coins',
            field=models.PositiveSmallIntegerField(default=90, help_text='Threshold for top coins/run, specified in percent', verbose_name='Top threshold for coins/run'),
        ),
        migrations.AddField(
            model_name='profile',
            name='settings_tracker_threshold_top_coins_hour',
            field=models.PositiveSmallIntegerField(default=90, help_text='Threshold for top coins/h, specified in percent', verbose_name='Top threshold for coins/h'),
        ),
    ]
