# Generated by Django 5.1.1 on 2024-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0006_relic_data_cherry_blossom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='bonus_type',
            field=models.CharField(choices=[('DAMAGE', 'Damage'), ('CRITFA', 'Critical Factor'), ('COINSB', 'Coins/Kill Bonus'), ('LABSPD', 'Lab Speed'), ('DEFABS', 'Defense Absolute'), ('DMGPME', 'Damage/Meter'), ('HEALTH', 'Health'), ('ATKSPD', 'Attack Speed'), ('CRITCH', 'Critical Chance')], help_text='The stat to be modified', max_length=6, verbose_name='Bonus Type'),
        ),
    ]
