# Generated by Django 5.1.1 on 2024-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0007_alter_relic_bonus_type'),
    ]

    def add_relics(apps, schema_editor):
        Relic = apps.get_model("penthouse", "Relic")

        Relic.objects.create(
            name="Lunar Cat Paw",
            rarity="RARE",
            bonus_type="CRITCH",
            bonus_value=1.0,
            source="E",
            condition="Meowy Night event; 350 medals"
        )
        Relic.objects.create(
            name="Pet Cat",
            rarity="EPIC",
            bonus_type="ATKSPD",
            bonus_value=2.0,
            source="E",
            condition="Meowy Night event; 700 medals"
        )

    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(add_relics, reverse),
    ]


