# Generated by Django 5.1.1 on 2025-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0008_relic_data_meowy_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='bonus_type',
            field=models.CharField(choices=[('DAMAGE', 'Damage'), ('CRITFA', 'Critical Factor'), ('COINSB', 'Coins/Kill Bonus'), ('LABSPD', 'Lab Speed'), ('DEFABS', 'Defense Absolute'), ('DMGPME', 'Damage/Meter'), ('HEALTH', 'Health'), ('ATKSPD', 'Attack Speed'), ('CRITCH', 'Critical Chance'), ('ULTDMG', 'Ultimate Damage'), ('FATKUP', 'Free Attack Upgrade')], help_text='The stat to be modified', max_length=6, verbose_name='Bonus Type'),
        ),
    ]
