# Generated by Django 5.1.1 on 2024-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0009_alter_relic_bonus_type'),
    ]

    def add_relics(apps, schema_editor):
        Relic = apps.get_model("penthouse", "Relic")

        Relic.objects.create(
            name="Confetti Ball",
            rarity="RARE",
            bonus_type="FATKUP",
            bonus_value=1.0,
            source="E",
            condition="New Year event (2025); 350 medals"
        )
        Relic.objects.create(
            name="Party Mask",
            rarity="EPIC",
            bonus_type="ULTDMG",
            bonus_value=5.0,
            source="E",
            condition="New Year event (2025); 700 medals"
        )

    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(add_relics, reverse),
    ]


