# Generated by Django 5.1.1 on 2024-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0010_relic_data_new_year_2025'),
    ]

    def add_relics(apps, schema_editor):
        Relic = apps.get_model("penthouse", "Relic")

        Relic.objects.create(
            name="Summit Starlight",
            rarity="RARE",
            bonus_type="LABSPD",
            bonus_value=2.0,
            source="E",
            condition="Howling Wolf event (2025); 350 medals"
        )
        Relic.objects.create(
            name="Mountain Goat",
            rarity="EPIC",
            bonus_type="HEALTH",
            bonus_value=5.0,
            source="E",
            condition="Howling Wolf event (2025); 700 medals"
        )

    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(add_relics, reverse),
    ]


