# Generated by Django 5.1.1 on 2025-01-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0013_relic_data_gravity_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the datapoint', verbose_name='Date')),
                ('ltc', models.PositiveBigIntegerField(help_text='Current Life Time Coins (LTC)', verbose_name='LTC')),
                ('lts', models.PositiveIntegerField(help_text='Current Life Time Stones (LTS)', verbose_name='LTS')),
                ('notes', models.TextField(help_text='Additional notes', verbose_name='Notes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Meta Datapoint',
                'verbose_name_plural': 'Meta Datapoints',
            },
        ),
    ]
