# Generated by Django 5.1.1 on 2025-01-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0014_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['date'], 'verbose_name': 'Meta Datapoint', 'verbose_name_plural': 'Meta Datapoints'},
        ),
    ]
