# Generated by Django 5.1.1 on 2025-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0015_alter_metadata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='relic',
            name='bonus_unit',
            field=models.CharField(default='%', help_text='Unit of the bonus value', max_length=3, verbose_name='Bonus Unit'),
        ),
    ]
