# Generated by Django 5.1.1 on 2025-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0018_relic_data_retro_arcade_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='bonus_type',
            field=models.CharField(choices=[('DAMAGE', 'Damage'), ('CRITFA', 'Critical Factor'), ('COINSB', 'Coins/Kill Bonus'), ('LABSPD', 'Lab Speed'), ('DEFABS', 'Defense Absolute'), ('DMGPME', 'Damage/Meter'), ('HEALTH', 'Health'), ('ATKSPD', 'Attack Speed'), ('CRITCH', 'Critical Chance'), ('ULTDMG', 'Ultimate Damage'), ('FATKUP', 'Free Attack Upgrade'), ('FDEFUP', 'Free Defense Upgrade'), ('SCRITC', 'Super Crit Chance'), ('BOTRNG', 'Bot Range'), ('HREGEN', 'Health Regen'), ('THORNS', 'Thorns')], help_text='The stat to be modified', max_length=6, verbose_name='Bonus Type'),
        ),
    ]
