# Generated by Django 5.1.1 on 2025-02-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0020_relic_data_deep_blue_sea_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this milestone', max_length=255, verbose_name='Title')),
                ('date_added', models.DateTimeField(help_text='Date this milestone was added', verbose_name='Date of creation')),
                ('date_completed', models.DateField(help_text='Date this milestone was completed', verbose_name='Date of completion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Progress Planning Milestone',
                'verbose_name_plural': 'Progress Planning Milestones',
            },
        ),
        migrations.CreateModel(
            name='MilestoneSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Caption of this section', max_length=255, verbose_name='Section')),
                ('resource', models.CharField(choices=[('COINS', 'Coins'), ('CASH', 'Cash'), ('STONE', 'Stones'), ('GEMS', 'Gems'), ('SHARD', 'Shards'), ('DICE', 'Reroll Shards'), ('KEYS', 'Keys'), ('MEDAL', 'Medals')], help_text='Required resource', max_length=5, verbose_name='Resource')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.milestone', verbose_name='Milestone Section')),
            ],
            options={
                'verbose_name': 'Progress Planning Section',
                'verbose_name_plural': 'Progress Planning Sections',
            },
        ),
        migrations.CreateModel(
            name='MilestoneStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penthouse.milestonesection', verbose_name='Milestone Step')),
            ],
            options={
                'verbose_name': 'Progress Planning Step',
                'verbose_name_plural': 'Progress Planning Step',
            },
        ),
    ]
