# Generated by Django 5.1.1 on 2025-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0024_relic_data_guild_season_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='date_completed',
            field=models.DateField(blank=True, help_text='Date this milestone was completed', null=True, verbose_name='Date of completion'),
        ),
    ]
