# Generated by Django 5.1.1 on 2025-03-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0025_alter_milestone_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonesection',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_sections', to='penthouse.milestone', verbose_name='Milestone Section'),
        ),
        migrations.AlterField(
            model_name='milestonestep',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_steps', to='penthouse.milestonesection', verbose_name='Milestone Step'),
        ),
    ]
