# Generated by Django 5.1.1 on 2025-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0026_alter_milestonesection_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonestep',
            name='step_value',
            field=models.CharField(default='0', help_text='Value of this step', max_length=50, verbose_name='Value'),
        ),
    ]
