# Generated by Django 5.1.1 on 2025-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0027_milestonestep_step_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonestep',
            name='completed',
            field=models.BooleanField(default=False, help_text='Determine if this step is already completed', verbose_name='step completion status'),
        ),
    ]
