# Generated by Django 5.1.1 on 2025-03-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0028_milestonestep_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonesection',
            name='resource',
            field=models.CharField(choices=[('COINS', 'Coins'), ('CASH', 'Cash'), ('STONE', 'Stones'), ('GEMS', 'Gems'), ('SHARD', 'Shards'), ('DICE', 'Reroll Shards'), ('KEYS', 'Keys'), ('MEDAL', 'Medals'), ('LABS', 'Labs')], help_text='Required resource', max_length=5, verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='relic',
            name='source',
            field=models.CharField(choices=[('M', 'Milestone'), ('T', 'Tournament'), ('E', 'Event'), ('O', 'Other'), ('G', 'Guild Event')], help_text='Source of the relic', max_length=1, verbose_name='Source'),
        ),
    ]
