# Generated by Django 5.1.1 on 2025-03-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penthouse', '0029_alter_milestonesection_resource_alter_relic_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='bonus_type',
            field=models.CharField(choices=[('DAMAGE', 'Damage'), ('CRITFA', 'Critical Factor'), ('COINSB', 'Coins/Kill Bonus'), ('LABSPD', 'Lab Speed'), ('DEFABS', 'Defense Absolute'), ('DMGPME', 'Damage/Meter'), ('HEALTH', 'Health'), ('ATKSPD', 'Attack Speed'), ('CRITCH', 'Critical Chance'), ('ULTDMG', 'Ultimate Damage'), ('FATKUP', 'Free Attack Upgrade'), ('FDEFUP', 'Free Defense Upgrade'), ('SCRITC', 'Super Crit Chance'), ('BOTRNG', 'Bot Range'), ('HREGEN', 'Health Regen'), ('THORNS', 'Thorns'), ('CASHBO', 'Cash Bonus'), ('ORBSPD', 'Orb Speed'), ('WALLRE', 'Wall Rebuild'), ('SCRITM', 'Super Crit Mult')], help_text='The stat to be modified', max_length=6, verbose_name='Bonus Type'),
        ),
    ]
